Add Vagrant VM and Docker container
Even though we are using create-react-app to bootstrap the project, we
still want it to conform to our development environment standards of
using an Vagrant VM to run Docker containers. The changes here are a
merge of the civic apps app template with some improvements from one of
our more recent projects.

diff --git a/scripts/test b/scripts/test
--- a/scripts/test
+++ b/scripts/test
@@ -1,5 +1,4 @@
 #!/bin/bash
-
 set -e
 
 if [[ -n "${ISM_DEBUG}" ]]; then
@@ -7,17 +6,36 @@ if [[ -n "${ISM_DEBUG}" ]]; then
 fi
 
 function usage() {
-    echo -n "Usage: $(basename "$0")
+    echo -n "Usage: $(basename "$0") [OPTION]
+
 Run linters and tests.
+
+Options:
+    -h --help       Display this help text
+    --git           Check git commit titles
 "
 }
 
-if [ "${BASH_SOURCE[0]}" = "${0}" ]
-then
-    if [ "${1:-}" = "--help" ]
-    then
-        usage
-    else
-        yarn test
+function app_tests() {
+    docker-compose \
+        -f docker-compose.yml \
+        run --rm \
+        -e "CI=true" \
+        app yarn test
+}
+
+function git_tests() {
+    # Fail build if any commit title in this branch contains these words
+    if git log --oneline develop... | grep -wiE "fixup|squash|wip"; then
+        echo "ERROR: Please squash all changes before merging."
+        exit 1
     fi
+}
+
+if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
+    case "${1:-}" in
+        -h|--help) usage ;;
+        --git)     git_tests ;;
+        *)         app_tests ;;
+    esac
 fi
